### ISSUE TITLE
Logos auf Header repositionieren

### ISSUE THREAD

**Issue by SimJoSt** [genofire/breminale.ffhb.de#5]
Meiner Meinung nach sollten beide Logos auf dem Header ein wenig höher sein und näher zusammen rücken.
- Das Freifunk Logo sollte das Gras gerade so nicht mehr berühren, dafür müsste es kleiner skaliert sein und ein bisschen nach oben rutschen.
- Das Breminale Logo ist schon gut, aber hat recht viel freien Platz nach oben und sollte den nutzen.
- Auf einem Desktop sieht ist die Positionierung sonst gut, aber auf einem Mobilgerät ist der Header recht breit und länglich. DIe Logos kommen nicht sehr stark zum tragen, da klein.  
  Ich würde den Abstand zum "goes" vom Breminale Stempel mindestens halbieren und das Freifunk-Logo auf den gleichen Abstand setzen.

**Comment by genofire** [comment]
Besser?
Ansonsten sollten wir uns dafür wahrscheinlich eher zusammensetzen!

**Comment by SimJoSt** [comment]
Auf meinem mobilen Gerät hat sich nichts geändert mach meinen Vorstellungen.
Nur das "goes" ist verschwunden... ;-)
EDIT: Ich sehe gerade, dass das "goes" gar nicht in die Grafik integriert ist. Auf meinem Mobilgerät wird es nicht angezeigt. Und wenn ich ins Repo gucke wohl das Gras auch nicht.
Aber für mich hat sich auf dem Desktop nichts geändert.
