### ISSUE TITLE
Anpassungen Feed-Bereich

### ISSUE THREAD

**Issue by SimJoSt** [genofire/breminale.ffhb.de#6]
Der Titel dieses Bereiches soll in "Breminale Facebook Feed" umbenannt werden.
"Filter:" soll entfernt werden. Die Buttons erklären sich von selbst.
Der Button "Alles" soll in "alle Posts" umbenannt werden.
"Aktualisieren:" soll verschwinden und stattdessen auf dem Aktualisieren-Button erscheinen.
Der Aktualisieren Button soll rechtsbündig eine Zeile unter den Filter-Buttons erscheinen.

**Comment by genofire** [comment]
Done, bis auf:
Der Aktualisieren Button soll rechtsbündig eine Zeile unter den Filter-Buttons erscheinen.

**Comment by genofire** [comment]
So nun auch fertig. 
War es so gemeint?

**Comment by SimJoSt** [comment]
Genauso wars gemeint.
Ich finde aber den Zeilenumbruch doch unsinnig. Nur rechtsbündig reicht.
